//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiscalCode.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FiscalCode.Resources.Languages.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Version: 2.0.3&lt;br /&gt;
        ///Author: Tommaso Scalici&lt;br /&gt;
        ///Privacy disclaimer:
        ///&lt;a href=&quot;http://tommasoscalici.altervista.org/fiscal_code_privacy_policy.html&quot; target=&quot;_blank&quot;&gt;
        ///     Privacy Policy
        ///&lt;/a&gt;
        ///
        ///&lt;br /&gt;&lt;br /&gt;
        ///
        ///&lt;strong&gt;Attention&lt;/strong&gt;:&lt;br /&gt;
        ///This application calculates the tax identification code using an algorithm from an external service.&lt;br /&gt;
        ///The algorithm is not able to distinguish cases of homocody.&lt;br /&gt;
        ///Please remember that the only 100% reliable tax identification code is the one issued  [stringa troncata]&quot;;.
        /// </summary>
        internal static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tax Code.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Birthdate.
        /// </summary>
        internal static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Birthdate is required!.
        /// </summary>
        internal static string BirthdateError {
            get {
                return ResourceManager.GetString("BirthdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert a date in a valid format! No future dates allowed!.
        /// </summary>
        internal static string BirthdateValidationError {
            get {
                return ResourceManager.GetString("BirthdateValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Birthplace.
        /// </summary>
        internal static string Birthplace {
            get {
                return ResourceManager.GetString("Birthplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Birthplace is required!.
        /// </summary>
        internal static string BirthplaceError {
            get {
                return ResourceManager.GetString("BirthplaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Italian city or foreign state.
        /// </summary>
        internal static string BirthplacePlaceholder {
            get {
                return ResourceManager.GetString("BirthplacePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fill in the data.
        /// </summary>
        internal static string FillData {
            get {
                return ResourceManager.GetString("FillData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a First name is required!.
        /// </summary>
        internal static string FirstNameError {
            get {
                return ResourceManager.GetString("FirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Last name is required!.
        /// </summary>
        internal static string LastNameError {
            get {
                return ResourceManager.GetString("LastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reorder.
        /// </summary>
        internal static string Reorder {
            get {
                return ResourceManager.GetString("Reorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scan card.
        /// </summary>
        internal static string ScanCard {
            get {
                return ResourceManager.GetString("ScanCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sex.
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sex is required!.
        /// </summary>
        internal static string SexError {
            get {
                return ResourceManager.GetString("SexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New tax code added succesfully.
        /// </summary>
        internal static string SuccessAdd {
            get {
                return ResourceManager.GetString("SuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tax code copied to clipboard.
        /// </summary>
        internal static string SuccessCopy {
            get {
                return ResourceManager.GetString("SuccessCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tax code deleted succesfully.
        /// </summary>
        internal static string SuccessDelete {
            get {
                return ResourceManager.GetString("SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tax code edited succesfully.
        /// </summary>
        internal static string SuccessEdit {
            get {
                return ResourceManager.GetString("SuccessEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Whoops... something went wrong.
        /// </summary>
        internal static string Whoops {
            get {
                return ResourceManager.GetString("Whoops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
